### ISSUE TITLE
Was this inspired by...

### ISSUE THREAD

**Issue by joelpittet** [andykent/jquery-humanize-messages-plugin#2]
http://code.google.com/p/humanmsg/

If so you may want to make note of his work.

**Comment by andykent** [comment]
Actually, no. I've never seen that project before now so thanks for pointing it out to me.

As the github description explains, it was inspired by this post from 2006...
http://humanized.com/weblog/2006/09/11/monolog_boxes_and_transparent_messages/

...interestingly the google code repo you point to also mentions this post so I guess we both had the same idea off the back of the same blog post.

There are obviously several implementations of this technique around these days and this repository has gone largely unmaintained for quite a while. That said, we do use this in production on a reasonable size site without any issues.

Can I ask, what prompted you to open this ticket? Are you the author of the other library and feel I have wronged you in some way?

To be honest I feel quite offended as I always try to give credit where it's due. In future you may want to avoid throwing accusations about other peoples contributions around.

**Comment by joelpittet** [comment]
Honestly, they looked so similar in name and utility I thought you may have forgot to mention them in the inspirations section.  It's clear you care, just thought you would like to make note.  Also your script doesn't have a little demo so I also though you may want to add one and theirs illustrates the idea well.

I am going to rewrite the plugin and may incorporate your mousemove catching if you don't mind?  Of course I will note you're contribution;)
